<?php
        setcookie('user_name',$_COOKIE['user_name'],time()-3600);
        setcookie('error1',$_COOKIE['error1'],time()-3600);
        setcookie('error2',$_COOKIE['error2'],time()-3600);
        setcookie('error3',$_COOKIE['error3'],time()-3600);
        setcookie('show',$_COOKIE['show'],time()-3600);
        setcookie('button',$_COOKIE['button'],time()-3600);
        setcookie('value',$_COOKIE['value'],time()-3600);
        setcookie('eid',$_COOKIE['eid'],time()-3600);
        setcookie('b_error',$_COOKIE['b_error'],time()-3600);
        setcookie('c_error',$_COOKIE['c_error'],time()-3600);
        setcookie('status',$_COOKIE['status'],time()-3600);
        setcookie('nodata',$_COOKIE['nodata'],time()-3600);
        setcookie('s_error',$_COOKIE['s_error'],time()-3600);
?>
